export enum Role {
  USERS = 'ROLE_STARGAZER_USERS',
  ADMINISTRATORS = 'ROLE_STARGAZER_ADMINISTRATORS',
  RESOURCE_MANAGER = 'ROLE_STARGAZER_RESOURCE_MANAGER',
  PRICING_ADMIN = 'ROLE_STARGAZER_PRICING_ADMIN',
  BILLING_ADMIN = 'ROLE_STARGAZER_BILLING_ADMIN',
  VIEWER = 'ROLE_STARGAZER_VIEWER',
}
