import {
  CityCombobox,
  Country,
  EventSearchCriteria,
  EventSearchResultData,
  OrganizationSearchResultDTO,
  SearchOrganizationFormValue,
  YesNoOption,
} from '@models/models';

export const eventSearchResultData: EventSearchResultData[] = [
  {
    notes: true,
    no: 1,
    periodBegin: [2021, 1, 1],
    periodEnd: [2021, 1, 1],
    description: 'event 1',
    eventType: 'type 1',
    city: 'city 1',
    status: 'status 1',
    deadline: [2021, 1, 1],
    category: 'category 1',
    subCategory: 'sub-category 1',
    office: 'office 1',
    quoteId: 'quote id 1',
    isPMO: true,
    id: 1,
    isParent: false,
    parent: false,
    contract: 'a',
    salesDeal: 'NEWS-LN',
  },
  {
    notes: false,
    no: 2,
    periodBegin: [2023, 1, 1],
    periodEnd: [2022, 1, 1],
    description: 'event 2',
    eventType: 'type 2',
    city: 'city 2',
    status: 'status 2',
    deadline: [2020, 1, 1],
    category: 'category 2',
    subCategory: 'sub-category 2',
    office: 'office 2',
    quoteId: 'quote id 2',
    isPMO: false,
    id: 1,
    isParent: false,
    parent: false,
    contract: 'b',
    salesDeal: 'NEWS-LN',
  },
];

export const organizationSearchResultDTO: OrganizationSearchResultDTO[] = [
  {
    id: 1,
    version: 1,
    code: 'ORG001',
    name: 'Organization 1',
    country: {
      version: 1,
      id: 101,
      code: 'US',
      name: 'United States',
      alias1: 'USA',
      alias2: 'America',
      alias3: 'US of A',
      extName: 'United States of America',
      extView: true,
      daylightSavingTime: true,
      usRestriction: false,
      area: {
        version: 1,
        id: 1001,
        sequence: 1,
        keyCode: 'US',
        code: 'US',
        isoCode: null,
        externalCode: 'US',
        label: 'United States',
        extView: true,
        externalLabel: 'United States',
        itemStatus: 'Active',
        businessKey: 'US',
        new: false,
      },
      businessKey: 'USA',
      new: false,
    },
    financialStatusType: 'OK',
    type: 'Type A',
    customer: 'Yes',
    provider: 'No',
    active: 'Yes',
    defaultCity: {
      id: 10001,
      code: 'NYC',
      name: 'New York City',
      alias1: 'NY',
      alias2: 'The Big Apple',
      alias3: 'City That Never Sleeps',
      country: {
        version: 1,
        id: 101,
        code: 'US',
        name: 'United States',
        alias1: 'USA',
        alias2: 'America',
        alias3: 'US of A',
        extName: 'United States of America',
        extView: true,
        daylightSavingTime: true,
        usRestriction: false,
        area: {
          version: 1,
          id: 1001,
          sequence: 1,
          keyCode: 'US',
          code: 'US',
          isoCode: null,
          externalCode: 'US',
          label: 'United States',
          extView: true,
          externalLabel: 'United States',
          itemStatus: 'Active',
          businessKey: 'US',
          new: false,
        },
        businessKey: 'USA',
        new: false,
      },
      extName: 'New York City',
      utc: 'UTC-5',
      extView: 'NYC',
      businessKey: 'NYC',
      new: false,
    },
    defaultPhone: '+1 (123) 456-7890',
    poRefMandatory: 'No',
    billedCurrencyLocked: 'Yes',
    defaultMail: 'b@b',
    defaultSystem: {
      version: 1,
      id: 1001,
      sequence: 1,
      keyCode: 'SYS001',
      code: 'System 001',
      externalCode: 'SYS001',
      label: 'System 001',
      extView: true,
      externalLabel: 'System 001',
      itemStatus: 'Active',
      businessKey: 'SYS001',
      new: false,
    },
  },
  {
    id: 2,
    version: 1,
    code: 'ORG002',
    name: 'Organization 2',
    country: {
      version: 1,
      id: 102,
      code: 'FR',
      name: 'France',
      alias1: 'FRA',
      alias2: 'French Republic',
      alias3: 'La Belle France',
      extName: 'French Republic',
      extView: true,
      daylightSavingTime: false,
      usRestriction: false,
      area: {
        version: 1,
        id: 1002,
        sequence: 1,
        keyCode: 'FR',
        code: 'FR',
        isoCode: null,
        externalCode: 'FR',
        label: 'France',
        extView: true,
        externalLabel: 'France',
        itemStatus: 'Active',
        businessKey: 'FR',
        new: false,
      },
      businessKey: 'FRA',
      new: false,
    },
    financialStatusType: 'BL',
    type: 'Type B',
    customer: 'No',
    provider: 'Yes',
    active: 'No',
    defaultCity: {
      id: 10002,
      code: 'PAR',
      name: 'Paris',
      alias1: 'PAR',
      alias2: 'City of Love',
      alias3: 'Capital of France',
      country: {
        version: 1,
        id: 102,
        code: 'FR',
        name: 'France',
        alias1: 'FRA',
        alias2: 'French Republic',
        alias3: 'La Belle France',
        extName: 'French Republic',
        extView: true,
        daylightSavingTime: false,
        usRestriction: false,
        area: {
          version: 1,
          id: 1002,
          sequence: 1,
          keyCode: 'FR',
          code: 'FR',
          externalCode: 'FR',
          isoCode: null,
          label: 'France',
          extView: true,
          externalLabel: 'France',
          itemStatus: 'Active',
          businessKey: 'FR',
          new: false,
        },
        businessKey: 'FRA',
        new: false,
      },
      extName: 'Paris',
      utc: 'UTC+1',
      extView: 'PAR',
      businessKey: 'PAR',
      new: false,
    },
    defaultPhone: '+33 1 23 45 67 89',
    poRefMandatory: 'Yes',
    billedCurrencyLocked: 'No',
    defaultMail: 'a@a.com',
    defaultSystem: {
      version: 1,
      id: 1002,
      sequence: 2,
      keyCode: 'SYS002',
      code: 'System 002',
      externalCode: 'SYS002',
      label: 'System 002',
      extView: true,
      externalLabel: 'System 002',
      itemStatus: 'Active',
      businessKey: 'SYS002',
      new: false,
    },
  },
];

export const cities: CityCombobox[] = [
  {
    version: 0,
    id: 3605,
    code: 'ESBJ',
    name: 'ESBJERG',
    alias1: '',
    alias2: '',
    alias3: '',
    country: {
      version: 0,
      id: 170,
      code: 'DK',
      name: 'DENMARK',
      alias1: '',
      alias2: '',
      alias3: '',
      extName: '',
      extView: true,
      daylightSavingTime: false,
      usRestriction: false,
      area: {
        version: 0,
        id: 377,
        sequence: 10,
        keyCode: 'AREA@A_EUROPE',
        code: 'A_EUROPE',
        isoCode: null,
        externalCode: '',
        label: 'Europe',
        extView: true,
        externalLabel: '',
        itemStatus: 'ACTIVE',
        businessKey: 'AREA@A_EUROPE',
        new: false,
      },
      businessKey: 'DK',
      new: false,
    },
    extName: 'Esbjerg',
    utc: '+02:00',
    extView: '',
    businessKey: 'ESBJ',
    new: false,
  },
  {
    version: 0,
    id: 13973,
    code: 'ESCA',
    name: 'ESCALDES-ENGORDANY',
    alias1: '',
    alias2: '',
    alias3: '',
    country: {
      version: 0,
      id: 5,
      code: 'AD',
      name: 'ANDORRA',
      alias1: '',
      alias2: '',
      alias3: '',
      extName: '',
      extView: true,
      daylightSavingTime: true,
      usRestriction: false,
      area: {
        version: 0,
        id: 377,
        sequence: 10,
        keyCode: 'AREA@A_EUROPE',
        code: 'A_EUROPE',
        isoCode: null,
        externalCode: '',
        label: 'Europe',
        extView: true,
        externalLabel: '',
        itemStatus: 'ACTIVE',
        businessKey: 'AREA@A_EUROPE',
        new: false,
      },
      businessKey: 'AD',
      new: false,
    },
    extName: 'Escaldes-Engordany',
    utc: '+01:00',
    extView: '',
    businessKey: 'ESCA',
    new: false,
  },
  {
    version: 0,
    id: 3608,
    code: 'ESCD',
    name: 'ENSCHEDE',
    alias1: '',
    alias2: '',
    alias3: '',
    country: {
      version: 0,
      id: 479,
      code: 'NL',
      name: 'NETHERLANDS',
      alias1: '',
      alias2: '',
      alias3: '',
      extName: '',
      extView: true,
      daylightSavingTime: true,
      usRestriction: false,
      area: {
        version: 0,
        id: 377,
        sequence: 10,
        keyCode: 'AREA@A_EUROPE',
        code: 'A_EUROPE',
        isoCode: null,
        externalCode: '',
        label: 'Europe',
        extView: true,
        externalLabel: '',
        itemStatus: 'ACTIVE',
        businessKey: 'AREA@A_EUROPE',
        new: false,
      },
      businessKey: 'NL',
      new: false,
    },
    extName: 'Enschede',
    utc: '+01:00',
    extView: '',
    businessKey: 'ESCD',
    new: false,
  },
  {
    version: 0,
    id: 3611,
    code: 'ESCH',
    name: 'ESCHENBACH',
    alias1: '',
    alias2: '',
    alias3: '',
    country: {
      version: 0,
      id: 122,
      code: 'CH',
      name: 'SWITZERLAND',
      alias1: '',
      alias2: '',
      alias3: '',
      extName: '',
      extView: true,
      daylightSavingTime: true,
      usRestriction: false,
      area: {
        version: 0,
        id: 377,
        sequence: 10,
        keyCode: 'AREA@A_EUROPE',
        code: 'A_EUROPE',
        isoCode: null,
        externalCode: '',
        label: 'Europe',
        extView: true,
        externalLabel: '',
        itemStatus: 'ACTIVE',
        businessKey: 'AREA@A_EUROPE',
        new: false,
      },
      businessKey: 'CH',
      new: false,
    },
    extName: 'Eschenbach',
    utc: '+01:00',
    extView: '',
    businessKey: 'ESCH',
    new: false,
  },
];

export const countries: Country[] = [
  {
    version: 1,
    id: 1,
    code: 'US',
    name: 'United States',
    alias1: 'USA',
    alias2: '',
    alias3: '',
    extName: '',
    extView: false,
    daylightSavingTime: true,
    usRestriction: false,
    area: {
      version: 1,
      id: 1,
      sequence: 1,
      keyCode: 'US',
      code: 'US',
      isoCode: null,
      externalCode: '',
      label: 'United States',
      extView: false,
      externalLabel: '',
      itemStatus: '',
      businessKey: '',
      new: false,
    },
    businessKey: '',
    new: false,
  },
  {
    version: 1,
    id: 2,
    code: 'US',
    name: 'Spain',
    alias1: 'SPA',
    alias2: '',
    alias3: '',
    extName: '',
    extView: false,
    daylightSavingTime: true,
    usRestriction: false,
    area: {
      version: 1,
      id: 2,
      sequence: 1,
      keyCode: 'SPA',
      code: 'SPA',
      isoCode: null,
      externalCode: '',
      label: 'Spain',
      extView: false,
      externalLabel: '',
      itemStatus: '',
      businessKey: '',
      new: false,
    },
    businessKey: '',
    new: false,
  },
];

export const mockEventSearchCriteria: EventSearchCriteria = {
  no: '123',
  periodBegin: [2022, 1, 1],
  periodEnd: [2022, 12, 31],
  eventTypeList: ['Conference', 'Seminar'],
  statusList: 'Approved',
  bureauList: 'Marketing',
  mediaList: 'Social Media',
  isParent: true,
  isPMO: false,
  city: 'New York',
  quoteId: 'Q123',
  userGroup: ['Admin', 'Finance'],
  parent: false,
};

export const organizationFormValue: SearchOrganizationFormValue = {
  code: 'ORG001',
  name: 'Organization 1',
  type: ['Type 1', 'Type 2'],
  country: ['USA', 'Canada'],
  defaultCity: ['New York', 'Toronto'],
  financialStatusType: ['Active', 'Inactive'],
  isCustomer: [YesNoOption.Yes],
  isProvider: [YesNoOption.Yes],
  isActive: [YesNoOption.Yes],
  isBilledCurrencyLocked: [YesNoOption.Yes],
  isPoRefMandatory: [YesNoOption.Yes],
};
